[package]
name = "nucleus-dev"
version.workspace = true
edition.workspace = true

[dependencies]
nucleus-plugin.workspace = true
serde.workspace = true
serde_json.workspace = true
async-trait = "0.1"
